// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wadzjfyhpalchlhidlyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhZHpqZnlocGFsY2hsaGlkbHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NDc3MzQsImV4cCI6MjA1MjUyMzczNH0.3OP09SYu9cqPipu_Gk6T8M7ZgMu8CkJSTdeN1_Y57Wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);